# ---------Stage 1 (install maven and maven ) (download JAR file)

FROM maven:3.8.3-openjdk-17 as builder

WORKDIR /src

COPY . /src

RUN mvn clean install -DskipTests=True

# ---------Stage 2 (install JRE and copy JAR file from stage 1)

FROM openjdk:17-alpine

COPY --from=builder /src/target/*.jar /src/target/bankapp.jar

EXPOSE 8080 

CMD ["java","-jar","/src/target/bankapp.jar"]